// <auto-generated />
namespace CodeFirstDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class NewType5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewType5));
        
        string IMigrationMetadata.Id
        {
            get { return "201404020744031_NewType5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
