//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18010
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSExpress.MvcApplication.App_Start {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppLocale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLocale() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMSExpress.MvcApplication.App_Start.AppLocale", typeof(AppLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 客户 的本地化字符串。
        /// </summary>
        internal static string model_customer {
            get {
                return ResourceManager.GetString("model_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组织架构 的本地化字符串。
        /// </summary>
        internal static string model_department {
            get {
                return ResourceManager.GetString("model_department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单 的本地化字符串。
        /// </summary>
        internal static string model_permission {
            get {
                return ResourceManager.GetString("model_permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        internal static string model_role {
            get {
                return ResourceManager.GetString("model_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        internal static string model_user {
            get {
                return ResourceManager.GetString("model_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除{0}失败，原因：{1} 的本地化字符串。
        /// </summary>
        internal static string webdata_delete_failure {
            get {
                return ResourceManager.GetString("webdata_delete_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除{0}成功 的本地化字符串。
        /// </summary>
        internal static string webdata_delete_success {
            get {
                return ResourceManager.GetString("webdata_delete_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载{0}失败，原因：{1} 的本地化字符串。
        /// </summary>
        internal static string webdata_load_failure {
            get {
                return ResourceManager.GetString("webdata_load_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存{0}失败，原因：{1} 的本地化字符串。
        /// </summary>
        internal static string webdata_save_failure {
            get {
                return ResourceManager.GetString("webdata_save_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存{0}成功 的本地化字符串。
        /// </summary>
        internal static string webdata_save_success {
            get {
                return ResourceManager.GetString("webdata_save_success", resourceCulture);
            }
        }
    }
}
